#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDC_PARTITION                           4294967295
#define IDC_CONFIGWINDOW                        1
#define IDC_CONFIGBOXINFO                       100
#define IDC_STATICPRIM                          101
#define IDC_STATICSEC                           102
#define IDC_CONFIGBOX                           103
#define IDC_LABEL00                             104
#define IDC_LABEL01                             105
#define IDC_LABEL02                             106
#define IDC_LABEL03                             107
#define IDC_LABEL04                             108
#define IDC_LABEL05                             109
#define IDC_LABEL06                             110
#define IDC_LABEL07                             111
#define IDC_LABEL08                             112
#define IDC_LABEL09                             113
#define IDC_LABEL10                             114
#define IDC_LABEL11                             115
#define IDC_LABEL12                             116
#define IDC_LABEL13                             117
#define IDC_LABEL14                             118
#define IDC_LABEL15                             119
#define IDC_LABEL16                             120
#define IDC_PRIMARY00                           121
#define IDC_PRIMARY01                           122
#define IDC_PRIMARY02                           123
#define IDC_PRIMARY03                           124
#define IDC_PRIMARY04                           125
#define IDC_PRIMARY05                           126
#define IDC_PRIMARY06                           127
#define IDC_PRIMARY07                           128
#define IDC_PRIMARY08                           129
#define IDC_PRIMARY09                           130
#define IDC_PRIMARY10                           131
#define IDC_PRIMARY11                           132
#define IDC_PRIMARY12                           133
#define IDC_PRIMARY13                           134
#define IDC_PRIMARY14                           135
#define IDC_PRIMARY15                           136
#define IDC_PRIMARY16                           137
#define IDC_SECONDARY00                         138
#define IDC_SECONDARY01                         139
#define IDC_SECONDARY02                         140
#define IDC_SECONDARY03                         141
#define IDC_SECONDARY04                         142
#define IDC_SECONDARY05                         143
#define IDC_SECONDARY06                         144
#define IDC_SECONDARY07                         145
#define IDC_SECONDARY08                         146
#define IDC_SECONDARY09                         147
#define IDC_SECONDARY10                         148
#define IDC_SECONDARY11                         149
#define IDC_SECONDARY12                         150
#define IDC_SECONDARY13                         151
#define IDC_SECONDARY14                         152
#define IDC_SECONDARY15                         153
#define IDC_SECONDARY16                         154
#define IDC_MOUSESELECT                         157
#define IDC_KEYBOARDSELECT                      158
#define IDC_KEYBOARDSELECTINFO                  160
#define IDE_TAB_STICK                           162
#define IDD_TAB_GYRO                            163
#define IDF_TAB_OTHER                           165
#define IDC_ALLPLAYERS                          174
#define IDC_RATIOSTATIC                         175
#define IDC_RATIOWIDTH                          176
#define IDC_RATIOSTATICX                        177
#define IDC_RATIOHEIGHT                         178
#define IDC_RESETFOV                            179
#define IDC_FOV_DEGREES                         180
#define IDC_FOV                                 181
#define IDC_FOV_NOTE                            182
#define IDC_GESHOWCROSSHAIR                     183
#define IDC_INFOBOX                             184
#define IDC_INFO                                185
#define IDC_REVERT                              186
#define IDC_OK                                  187
#define IDC_CANCEL                              188
#define IDC_CLEAR                               189
#define IDC_HELPPOPUP                           190
#define IDC_PLAYER1                             191
#define IDC_PLAYER2                             192
#define IDC_PLAYER3                             193
#define IDC_PLAYER4                             194
#define IDC_DETECTDEVICE                        195
#define IDC_DEVICETYPEBOX                       40000
#define IDD_GYRO_SENSITIVITY_Y_LABEL            40000
#define IDF_USESTICKTOAIM                       40000
#define IDC_DEVICECLASSTEXT                     40001
#define IDD_GYRO_SENSITIVITY_X                  40001
#define IDE_STICK_AIM_SELECTOR_LEFT             40001
#define IDF_INVERTPITCH                         40001
#define IDC_DEVICEPRIMARYINFO                   40002
#define IDD_GYRO_SENSITIVITY_X_BOX              40002
#define IDE_STICK_MODE                          40002
#define IDF_PDCURSORAIMING                      40002
#define IDC_PSETTINGS_TABS                      40003
#define IDD_GYRO_SENSITIVITY_Y_BOX              40003
#define IDE_STICK_AIM_SENSITIVITY_X             40003
#define IDF_CROUCHTOGGLE                        40003
#define IDD_GYRO_SENSITIVITY_Y                  40004
#define IDE_STICK_AIM_SENSITIVITY_TEXT          40004
#define IDD_GYRO_SENSITIVITY_LABEL              40005
#define IDE_STICK_AIM_SENSITIVITY_X_XLABEL      40005
#define IDF_GECURSORAIMING                      40005
#define IDD_GYRO_AIM_MODE                       40006
#define IDE_STICK_AIM_SENSITIVITY_Y             40006
#define IDE_STICK_AIM_SENSITIVITY_Y_TEXT        40007
#define IDD_GYRO_AIM_MODE_LABEL                 40008
#define IDE_STICK_AIM_DEADZONE_X_LABEL          40008
#define IDE_STICK_AIM_DEADZONE_Y_LABEL          40009
#define IDE_STICK_AIM_DEADZONE_X                40010
#define IDE_STICK_AIM_DEADZONE_X_TEXT           40011
#define IDE_STICK_MOVE_DEADZONE_TEXT            40012
#define IDE_STICK_AIM_DEADZONE_Y                40013
#define IDE_STICK_AIM_DEADZONE_Y_TEXT           40014
#define IDE_STICK_AIM_SENSITIVITIY_Y_LABEL      40015
#define IDE_STICK_MOVE_DEADZONE_X               40016
#define IDE_STICK_MOVE_DEADZONE_X_LABEL         40017
#define IDE_STICK_MOVE_DEADZONE_Y_LABEL         40018
#define IDE_STICK_MOVE_DEADZONE_Y               40019
#define IDE_STICK_MOVE_DEADZONE_Y_LABEL_TEXT    40020
#define IDE_STICK_AIM_SELECTOR_RIGHT            40021
#define IDE_STICK_AIM_SELECTOR_LABEL            40022
#define IDE_STICK_MODE_LABEL                    40023
